parameter_defaults:
  UpgradeLeappDevelSkip: "LEAPP_UNSUPPORTED=1 LEAPP_DEVEL_TARGET_RELEASE=8.4"
  LeappInitCommand: |
    for module in pata_acpi floppy;
    do
      sudo sed -i "/^${module}$/d" /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/kernel/checkkerneldrivers/files/removed_drivers.txt;
    done
    sudo rm -f /usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/persistentnetnamesdisable/actor.py
    sudo yum -y remove mariadb-server* || true
  UpgradeInitCommand: "sudo dnf config-manager --save --setopt exclude=''"
